#!/usr/bin/perl

use strict;
use warnings;

use OtoPerl::Client;

my $options = read_options({
	-host => 'localhost',
	-port => '14609'
}, \@ARGV);

test_input_files(\@ARGV);

OtoPerl::Client->send($options, @ARGV);



sub read_options {
	my $defaults = shift;
	my $arglist = shift;
	while ( $_ = shift @$arglist ) {
		if ($_ =~ /^\-\w+$/) {
			exists $defaults->{$_} or die "unknown option '$_'.";
			@$arglist or die "no value for option '$_'.";
			$defaults->{$_} = shift @$arglist;
		}else{
			unshift @$arglist, $_;
			return $defaults;
		}
	}
	@$arglist or die "no input files.";
}

sub test_input_files {
	my $arglist = shift;
	@$arglist or die "no input files.";
	foreach (@$arglist) {
		-r $_ or die "input file '$_' not exists or readable.";
	}
}
