#!/usr/bin/perl

use strict;
use warnings;

use OtoPerl::Client;

my $options = OtoPerl::Client::read_options({
	-host => 'localhost',
	-port => '14609',
	-h    => undef,
	-p    => undef,
}, \@ARGV);
defined $options->{-p} and $options->{-port} = $options->{-p};
defined $options->{-h} and $options->{-host} = $options->{-h};

$options->{-port} = OtoPerl::Client::find_port($options->{-port});

OtoPerl::Client::test_input_files(\@ARGV);

my @results = OtoPerl::Client->send($options, @ARGV);
foreach (0..$#results) {
	print "[$ARGV[$_]] ", 
		defined $results[$_] ? $results[$_] : "ok",
		"\n";
}
