#!/usr/bin/perl

use strict;
use warnings;

use OtoPerl::Client;

my $options = OtoPerl::Client::read_options({
	-host => 'localhost',
	-port => '14609'
}, \@ARGV);

OtoPerl::Client::test_input_files(\@ARGV);

OtoPerl::Client->send($options, @ARGV);

